=== api-evangelist/anilist/json-schema/anilist-review-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/anilist/refs/heads/main/json-schema/anilist-review-schema.json",
  "title": "Review",
  "description": "A Review that features in an anime or manga",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "description": "The id of the review"
    },
    "userId": {
      "type": "integer",
      "description": "The id of the review's creator"
    },
    "mediaId": {
      "type": "integer",
      "description": "The id of the review's media"
    },
    "mediaType": {
      "type": "string",
      "enum": [
        "ANIME",
        "MANGA"
      ],
      "description": "For which type of media the review is for"
    },
    "summary": {
      "type": "string",
      "description": "A short summary of the review"
    },
    "body": {
      "type": "string",
      "description": "The main review body text"
    },
    "rating": {
      "type": "integer",
      "description": "The total user rating of the review"
    },
    "ratingAmount": {
      "type": "integer",
      "description": "The amount of user ratings of the review"
    },
    "userRating": {
      "type": "string",
      "enum": [
        "NO_VOTE",
        "UP_VOTE",
        "DOWN_VOTE"
      ],
      "description": "The rating of the review by currently authenticated user"
    },
    "score": {
      "type": "integer",
      "description": "The review score of the media"
    },
    "private": {
      "type": "boolean",
      "description": "If the review is not yet publicly published and is only viewable by creator"
    },
    "siteUrl": {
      "type": "string",
      "description": "The url for the review page on the AniList website"
    },
    "createdAt": {
      "type": "integer",
      "description": "The time of the thread creation"
    },
    "updatedAt": {
      "type": "integer",
      "description": "The time of the thread last update"
    },
    "user": {
      "$ref": "./anilist-user-schema.json",
      "description": "The creator of the review"
    },
    "media": {
      "$ref": "./anilist-media-schema.json",
      "description": "The media the review is of"
    }
  },
  "required": [
    "id",
    "userId",
    "mediaId",
    "createdAt",
    "updatedAt"
  ]
}

=== api-evangelist/anilist/examples/anilist-review-example.json
{
  "id": 1,
  "userId": 1,
  "mediaId": 1,
  "mediaType": "ANIME",
  "summary": "Sample description.",
  "body": "string",
  "rating": 1,
  "ratingAmount": 1,
  "userRating": "NO_VOTE",
  "score": 87,
  "private": false,
  "siteUrl": "https://anilist.co/anime/1",
  "createdAt": 1748563200,
  "updatedAt": 1748563200,
  "user": {
    "id": 1,
    "name": "Sample Name",
    "about": "string",
    "avatar": {
      "large": "string",
      "medium": "string"
    },
    "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/example.jpg",
    "isFollowing": false,
    "isFollower": false,
    "isBlocked": false,
    "bans": {},
    "options": {
      "titleLanguage": "ROMAJI",
      "displayAdultContent": false,
      "airingNotifications": false,
      "profileColor": "#3DB4F2",
      "notificationOptions": [
        {}
      ],
      "timezone": "string",
      "activityMergeTime": 1748563200,
      "staffNameLanguage": "ROMAJI_WESTERN",
      "restrictMessagesToFollowing": false,
      "disabledListActivity": [
        {}
      ]
    },
    "mediaListOptions": {},
    "favourites": {},
    "statistics": {},
    "unreadNotificationCount": 1,
    "siteUrl": "https://anilist.co/anime/1",
    "donatorTier": 1,
    "donatorBadge": "string",
    "moderatorRoles": [
      "ADMIN"
    ],
    "createdAt": 1748563200,
    "updatedAt": 1748563200,
    "stats": {},
    "moderatorStatus": "string",
    "previousNames": [
      {}
    ]
  },
  "media": {
    "id": 1,
    "idMal": 1,
    "title": {
      "romaji": "Cowboy Bebop",
      "english": "Cowboy Bebop",
      "native": "カウボーイビバップ",
      "userPreferred": "string"
    },
    "type": "ANIME",
    "format": "TV",
    "status": "FINISHED",
    "description": "Sample description.",
    "startDate": {
      "year": 1998,
      "month": 4,
      "day": 3
    },
    "endDate": {
      "year": 1998,
      "month": 4,
      "day": 3
    },
    "season": "WINTER",
    "seasonYear": 1998,
    "seasonInt": 1,
    "episodes": 26,
    "duration": 24,
    "chapters": 0,
    "volumes": 0,
    "countryOfOrigin": "string",
    "isLicensed": false,
    "source": "ORIGINAL",
    "hashtag": "string",
    "trailer": {},
    "updatedAt": 1748563200,
    "coverImage": {
      "extraLarge": "string",
      "large": "string",
      "medium": "string",
      "color": "#3DB4F2"
    },
    "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/example.jpg",
    "genres": [
      "string"
    ],
    "synonyms": [
      "string"
    ],
    "averageScore": 87,
    "meanScore": 87,
    "popularity": 87,
    "isLocked": false,
    "trending": 100,
    "favourites": 87,
    "tags": [
      {}
    ],
    "relations": {},
    "characters": {},
    "staff": {},
    "studios": {},
    "isFavourite": false,
    "isFavouriteBlocked": false,
    "isAdult": false,
    "nextAiringEpisode": {
      "id": 1,
      "airingAt": 1748563200,
      "timeUntilAiring": 1748563200,
      "episode": 26,
      "mediaId": 1
    },
    "airingSchedule": {},
    "trends": {},
    "externalLinks": [
      {}
    ],
    "streamingEpisodes": [
      {}
    ],
    "rankings": [
      {}
    ],
    "mediaListEntry": {
      "id": 1,
      "userId": 1,
      "mediaId": 1,
      "status": "CURRENT",
      "score": 9.0,
      "progress": 1,
      "progressVolumes": 0,
      "repeat": 1748563200,
      "priority": 1,
      "private": false,
      "notes": "string",
      "hiddenFromStatusLists": false,
      "customLists": {},
      "advancedScores": {},
      "updatedAt": 1748563200,
      "createdAt": 1748563200
    },
    "reviews": {},
    "recommendations": {},
    "stats": {},
    "siteUrl": "https://anilist.co/anime/1",
    "autoCreateForumThread": false,
    "isRecommendationBlocked": false,
    "isReviewBlocked": false,
    "modNotes": "string"
  }
}
