=== api-evangelist/anilist/json-schema/anilist-thread-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/anilist/refs/heads/main/json-schema/anilist-thread-schema.json",
  "title": "Thread",
  "description": "Forum Thread",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "description": "The id of the thread"
    },
    "title": {
      "type": "string",
      "description": "The title of the thread"
    },
    "body": {
      "type": "string",
      "description": "The text body of the thread (Markdown)"
    },
    "userId": {
      "type": "integer",
      "description": "The id of the thread owner user"
    },
    "replyUserId": {
      "type": "integer",
      "description": "The id of the user who most recently commented on the thread"
    },
    "replyCommentId": {
      "type": "integer",
      "description": "The id of the most recent comment on the thread"
    },
    "replyCount": {
      "type": "integer",
      "description": "The number of comments on the thread"
    },
    "viewCount": {
      "type": "integer",
      "description": "The number of times users have viewed the thread"
    },
    "isLocked": {
      "type": "boolean",
      "description": "If the thread is locked and can receive comments"
    },
    "isSticky": {
      "type": "boolean",
      "description": "If the thread is stickied and should be displayed at the top of the page"
    },
    "isSubscribed": {
      "type": "boolean",
      "description": "If the currently authenticated user is subscribed to the thread"
    },
    "likeCount": {
      "type": "integer",
      "description": "The amount of likes the thread has"
    },
    "isLiked": {
      "type": "boolean",
      "description": "If the currently authenticated user liked the thread"
    },
    "repliedAt": {
      "type": "integer",
      "description": "The time of the last reply"
    },
    "createdAt": {
      "type": "integer",
      "description": "The time of the thread creation"
    },
    "updatedAt": {
      "type": "integer",
      "description": "The time of the thread last update"
    },
    "user": {
      "$ref": "./anilist-user-schema.json",
      "description": "The owner of the thread"
    },
    "replyUser": {
      "$ref": "./anilist-user-schema.json",
      "description": "The user to last reply to the thread"
    },
    "likes": {
      "type": "array",
      "items": {
        "$ref": "./anilist-user-schema.json"
      },
      "description": "The users who liked the thread"
    },
    "siteUrl": {
      "type": "string",
      "description": "The url for the thread page on the AniList website"
    },
    "categories": {
      "type": "array",
      "items": {
        "$ref": "./anilist-threadcategory-schema.json"
      },
      "description": "The categories of the thread"
    },
    "mediaCategories": {
      "type": "array",
      "items": {
        "$ref": "./anilist-media-schema.json"
      },
      "description": "The media categories of the thread"
    }
  },
  "required": [
    "id",
    "userId",
    "likeCount",
    "createdAt",
    "updatedAt"
  ]
}

=== api-evangelist/anilist/examples/anilist-thread-example.json
{
  "id": 1,
  "title": "Cowboy Bebop",
  "body": "string",
  "userId": 1,
  "replyUserId": 1,
  "replyCommentId": 1,
  "replyCount": 1,
  "viewCount": 1,
  "isLocked": false,
  "isSticky": false,
  "isSubscribed": false,
  "likeCount": 1,
  "isLiked": false,
  "repliedAt": 1748563200,
  "createdAt": 1748563200,
  "updatedAt": 1748563200,
  "user": {
    "id": 1,
    "name": "Sample Name",
    "about": "string",
    "avatar": {
      "large": "string",
      "medium": "string"
    },
    "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/example.jpg",
    "isFollowing": false,
    "isFollower": false,
    "isBlocked": false,
    "bans": {},
    "options": {
      "titleLanguage": "ROMAJI",
      "displayAdultContent": false,
      "airingNotifications": false,
      "profileColor": "#3DB4F2",
      "notificationOptions": [
        {}
      ],
      "timezone": "string",
      "activityMergeTime": 1748563200,
      "staffNameLanguage": "ROMAJI_WESTERN",
      "restrictMessagesToFollowing": false,
      "disabledListActivity": [
        {}
      ]
    },
    "mediaListOptions": {},
    "favourites": {},
    "statistics": {},
    "unreadNotificationCount": 1,
    "siteUrl": "https://anilist.co/anime/1",
    "donatorTier": 1,
    "donatorBadge": "string",
    "moderatorRoles": [
      "ADMIN"
    ],
    "createdAt": 1748563200,
    "updatedAt": 1748563200,
    "stats": {},
    "moderatorStatus": "string",
    "previousNames": [
      {}
    ]
  },
  "replyUser": {
    "id": 1,
    "name": "Sample Name",
    "about": "string",
    "avatar": {
      "large": "string",
      "medium": "string"
    },
    "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/example.jpg",
    "isFollowing": false,
    "isFollower": false,
    "isBlocked": false,
    "bans": {},
    "options": {
      "titleLanguage": "ROMAJI",
      "displayAdultContent": false,
      "airingNotifications": false,
      "profileColor": "#3DB4F2",
      "notificationOptions": [
        {}
      ],
      "timezone": "string",
      "activityMergeTime": 1748563200,
      "staffNameLanguage": "ROMAJI_WESTERN",
      "restrictMessagesToFollowing": false,
      "disabledListActivity": [
        {}
      ]
    },
    "mediaListOptions": {},
    "favourites": {},
    "statistics": {},
    "unreadNotificationCount": 1,
    "siteUrl": "https://anilist.co/anime/1",
    "donatorTier": 1,
    "donatorBadge": "string",
    "moderatorRoles": [
      "ADMIN"
    ],
    "createdAt": 1748563200,
    "updatedAt": 1748563200,
    "stats": {},
    "moderatorStatus": "string",
    "previousNames": [
      {}
    ]
  },
  "likes": [
    {
      "id": 1,
      "name": "Sample Name",
      "about": "string",
      "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/example.jpg",
      "isFollowing": false,
      "isFollower": false,
      "isBlocked": false,
      "bans": {},
      "unreadNotificationCount": 1,
      "siteUrl": "https://anilist.co/anime/1",
      "donatorTier": 1,
      "donatorBadge": "string",
      "moderatorRoles": [
        "ADMIN"
      ],
      "createdAt": 1748563200,
      "updatedAt": 1748563200,
      "moderatorStatus": "string",
      "previousNames": [
        {}
      ]
    }
  ],
  "siteUrl": "https://anilist.co/anime/1",
  "categories": [
    {}
  ],
  "mediaCategories": [
    {
      "id": 1,
      "idMal": 1,
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "Sample description.",
      "season": "WINTER",
      "seasonYear": 1998,
      "seasonInt": 1,
      "episodes": 26,
      "duration": 24,
      "chapters": 0,
      "volumes": 0,
      "countryOfOrigin": "string",
      "isLicensed": false,
      "source": "ORIGINAL",
      "hashtag": "string",
      "updatedAt": 1748563200,
      "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/example.jpg",
      "genres": [
        "string"
      ],
      "synonyms": [
        "string"
      ],
      "averageScore": 87,
      "meanScore": 87,
      "popularity": 87,
      "isLocked": false,
      "trending": 100,
      "favourites": 87,
      "tags": [
        {}
      ],
      "isFavourite": false,
      "isFavouriteBlocked": false,
      "isAdult": false,
      "externalLinks": [
        {}
      ],
      "streamingEpisodes": [
        {}
      ],
      "rankings": [
        {}
      ],
      "siteUrl": "https://anilist.co/anime/1",
      "autoCreateForumThread": false,
      "isRecommendationBlocked": false,
      "isReviewBlocked": false,
      "modNotes": "string"
    }
  ]
}
