=== api-evangelist/anilist/json-schema/anilist-media-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/anilist/refs/heads/main/json-schema/anilist-media-schema.json",
  "title": "Media",
  "description": "Anime or Manga",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "description": "The id of the media"
    },
    "idMal": {
      "type": "integer",
      "description": "The mal id of the media"
    },
    "title": {
      "$ref": "./anilist-mediatitle-schema.json",
      "description": "The official titles of the media in various languages"
    },
    "type": {
      "type": "string",
      "enum": [
        "ANIME",
        "MANGA"
      ],
      "description": "The type of the media; anime or manga"
    },
    "format": {
      "type": "string",
      "enum": [
        "TV",
        "TV_SHORT",
        "MOVIE",
        "SPECIAL",
        "OVA",
        "ONA",
        "MUSIC",
        "MANGA",
        "NOVEL",
        "ONE_SHOT"
      ],
      "description": "The format the media was released in"
    },
    "status": {
      "type": "string",
      "enum": [
        "FINISHED",
        "RELEASING",
        "NOT_YET_RELEASED",
        "CANCELLED",
        "HIATUS"
      ],
      "description": "The current releasing status of the media"
    },
    "description": {
      "type": "string",
      "description": "Short description of the media's story and characters"
    },
    "startDate": {
      "$ref": "./anilist-fuzzydate-schema.json",
      "description": "The first official release date of the media"
    },
    "endDate": {
      "$ref": "./anilist-fuzzydate-schema.json",
      "description": "The last official release date of the media"
    },
    "season": {
      "type": "string",
      "enum": [
        "WINTER",
        "SPRING",
        "SUMMER",
        "FALL"
      ],
      "description": "The season the media was initially released in"
    },
    "seasonYear": {
      "type": "integer",
      "description": "The season year the media was initially released in"
    },
    "seasonInt": {
      "type": "integer",
      "description": "The year & season the media was initially released in"
    },
    "episodes": {
      "type": "integer",
      "description": "The amount of episodes the anime has when complete"
    },
    "duration": {
      "type": "integer",
      "description": "The general length of each anime episode in minutes"
    },
    "chapters": {
      "type": "integer",
      "description": "The amount of chapters the manga has when complete"
    },
    "volumes": {
      "type": "integer",
      "description": "The amount of volumes the manga has when complete"
    },
    "countryOfOrigin": {
      "type": "string",
      "description": "Where the media was created. (ISO 3166-1 alpha-2)"
    },
    "isLicensed": {
      "type": "boolean",
      "description": "If the media is officially licensed or a self-published doujin release"
    },
    "source": {
      "type": "string",
      "enum": [
        "ORIGINAL",
        "MANGA",
        "LIGHT_NOVEL",
        "VISUAL_NOVEL",
        "VIDEO_GAME",
        "OTHER",
        "NOVEL",
        "DOUJINSHI",
        "ANIME",
        "WEB_NOVEL",
        "LIVE_ACTION",
        "GAME",
        "COMIC",
        "MULTIMEDIA_PROJECT",
        "PICTURE_BOOK"
      ],
      "description": "Source type the media was adapted from."
    },
    "hashtag": {
      "type": "string",
      "description": "Official Twitter hashtags for the media"
    },
    "trailer": {
      "$ref": "./anilist-mediatrailer-schema.json",
      "description": "Media trailer or advertisement"
    },
    "updatedAt": {
      "type": "integer",
      "description": "When the media's data was last updated"
    },
    "coverImage": {
      "$ref": "./anilist-mediacoverimage-schema.json",
      "description": "The cover images of the media"
    },
    "bannerImage": {
      "type": "string",
      "description": "The banner image of the media"
    },
    "genres": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "The genres of the media"
    },
    "synonyms": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Alternative titles of the media"
    },
    "averageScore": {
      "type": "integer",
      "description": "A weighted average score of all the user's scores of the media"
    },
    "meanScore": {
      "type": "integer",
      "description": "Mean score of all the user's scores of the media"
    },
    "popularity": {
      "type": "integer",
      "description": "The number of users with the media on their list"
    },
    "isLocked": {
      "type": "boolean",
      "description": "Locked media may not be added to lists our favorited. This may be due to the entry pending for deletion or other reasons."
    },
    "trending": {
      "type": "integer",
      "description": "The amount of related activity in the past hour"
    },
    "favourites": {
      "type": "integer",
      "description": "The amount of user's who have favourited the media"
    },
    "tags": {
      "type": "array",
      "items": {
        "$ref": "./anilist-mediatag-schema.json"
      },
      "description": "List of tags that describes elements and themes of the media"
    },
    "relations": {
      "$ref": "./anilist-mediaconnection-schema.json",
      "description": "Other media in the same or connecting franchise"
    },
    "characters": {
      "$ref": "./anilist-characterconnection-schema.json",
      "description": "The characters in the media"
    },
    "staff": {
      "$ref": "./anilist-staffconnection-schema.json",
      "description": "The staff who produced the media"
    },
    "studios": {
      "$ref": "./anilist-studioconnection-schema.json",
      "description": "The companies who produced the media"
    },
    "isFavourite": {
      "type": "boolean",
      "description": "If the media is marked as favourite by the current authenticated user"
    },
    "isFavouriteBlocked": {
      "type": "boolean",
      "description": "If the media is blocked from being added to favourites"
    },
    "isAdult": {
      "type": "boolean",
      "description": "If the media is intended only for 18+ adult audiences"
    },
    "nextAiringEpisode": {
      "$ref": "./anilist-airingschedule-schema.json",
      "description": "The media's next episode airing schedule"
    },
    "airingSchedule": {
      "$ref": "./anilist-airingscheduleconnection-schema.json",
      "description": "The media's entire airing schedule"
    },
    "trends": {
      "$ref": "./anilist-mediatrendconnection-schema.json",
      "description": "The media's daily trend stats"
    },
    "externalLinks": {
      "type": "array",
      "items": {
        "$ref": "./anilist-mediaexternallink-schema.json"
      },
      "description": "External links to another site related to the media"
    },
    "streamingEpisodes": {
      "type": "array",
      "items": {
        "$ref": "./anilist-mediastreamingepisode-schema.json"
      },
      "description": "Data and links to legal streaming episodes on external sites"
    },
    "rankings": {
      "type": "array",
      "items": {
        "$ref": "./anilist-mediarank-schema.json"
      },
      "description": "The ranking of the media in a particular time span and format compared to other media"
    },
    "mediaListEntry": {
      "$ref": "./anilist-medialist-schema.json",
      "description": "The authenticated user's media list entry for the media"
    },
    "reviews": {
      "$ref": "./anilist-reviewconnection-schema.json",
      "description": "User reviews of the media"
    },
    "recommendations": {
      "$ref": "./anilist-recommendationconnection-schema.json",
      "description": "User recommendations for similar media"
    },
    "stats": {
      "$ref": "./anilist-mediastats-schema.json"
    },
    "siteUrl": {
      "type": "string",
      "description": "The url for the media page on the AniList website"
    },
    "autoCreateForumThread": {
      "type": "boolean",
      "description": "If the media should have forum thread automatically created for it on airing episode release"
    },
    "isRecommendationBlocked": {
      "type": "boolean",
      "description": "If the media is blocked from being recommended to/from"
    },
    "isReviewBlocked": {
      "type": "boolean",
      "description": "If the media is blocked from being reviewed"
    },
    "modNotes": {
      "type": "string",
      "description": "Notes for site moderators"
    }
  },
  "required": [
    "id",
    "isFavourite",
    "isFavouriteBlocked"
  ]
}

=== api-evangelist/anilist/examples/anilist-media-example.json
{
  "id": 1,
  "idMal": 1,
  "title": {
    "romaji": "Cowboy Bebop",
    "english": "Cowboy Bebop",
    "native": "カウボーイビバップ",
    "userPreferred": "string"
  },
  "type": "ANIME",
  "format": "TV",
  "status": "FINISHED",
  "description": "Sample description.",
  "startDate": {
    "year": 1998,
    "month": 4,
    "day": 3
  },
  "endDate": {
    "year": 1998,
    "month": 4,
    "day": 3
  },
  "season": "WINTER",
  "seasonYear": 1998,
  "seasonInt": 1,
  "episodes": 26,
  "duration": 24,
  "chapters": 0,
  "volumes": 0,
  "countryOfOrigin": "string",
  "isLicensed": false,
  "source": "ORIGINAL",
  "hashtag": "string",
  "trailer": {},
  "updatedAt": 1748563200,
  "coverImage": {
    "extraLarge": "string",
    "large": "string",
    "medium": "string",
    "color": "#3DB4F2"
  },
  "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/example.jpg",
  "genres": [
    "string"
  ],
  "synonyms": [
    "string"
  ],
  "averageScore": 87,
  "meanScore": 87,
  "popularity": 87,
  "isLocked": false,
  "trending": 100,
  "favourites": 87,
  "tags": [
    {
      "id": 1,
      "name": "Sample Name",
      "description": "Sample description.",
      "category": "string",
      "rank": 1,
      "isGeneralSpoiler": false,
      "isMediaSpoiler": false,
      "isAdult": false,
      "userId": 1
    }
  ],
  "relations": {},
  "characters": {},
  "staff": {},
  "studios": {},
  "isFavourite": false,
  "isFavouriteBlocked": false,
  "isAdult": false,
  "nextAiringEpisode": {
    "id": 1,
    "airingAt": 1748563200,
    "timeUntilAiring": 1748563200,
    "episode": 26,
    "mediaId": 1,
    "media": {
      "id": 1,
      "idMal": 1,
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "Sample description.",
      "season": "WINTER",
      "seasonYear": 1998,
      "seasonInt": 1,
      "episodes": 26,
      "duration": 24,
      "chapters": 0,
      "volumes": 0,
      "countryOfOrigin": "string",
      "isLicensed": false,
      "source": "ORIGINAL",
      "hashtag": "string",
      "updatedAt": 1748563200,
      "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/example.jpg",
      "genres": [
        "string"
      ],
      "synonyms": [
        "string"
      ],
      "averageScore": 87,
      "meanScore": 87,
      "popularity": 87,
      "isLocked": false,
      "trending": 100,
      "favourites": 87,
      "tags": [
        {}
      ],
      "isFavourite": false,
      "isFavouriteBlocked": false,
      "isAdult": false,
      "externalLinks": [
        {}
      ],
      "streamingEpisodes": [
        {}
      ],
      "rankings": [
        {}
      ],
      "siteUrl": "https://anilist.co/anime/1",
      "autoCreateForumThread": false,
      "isRecommendationBlocked": false,
      "isReviewBlocked": false,
      "modNotes": "string"
    }
  },
  "airingSchedule": {},
  "trends": {},
  "externalLinks": [
    {}
  ],
  "streamingEpisodes": [
    {}
  ],
  "rankings": [
    {}
  ],
  "mediaListEntry": {
    "id": 1,
    "userId": 1,
    "mediaId": 1,
    "status": "CURRENT",
    "score": 9.0,
    "progress": 1,
    "progressVolumes": 0,
    "repeat": 1748563200,
    "priority": 1,
    "private": false,
    "notes": "string",
    "hiddenFromStatusLists": false,
    "customLists": {},
    "advancedScores": {},
    "startedAt": {
      "year": 1998,
      "month": 4,
      "day": 3
    },
    "completedAt": {
      "year": 1998,
      "month": 4,
      "day": 3
    },
    "updatedAt": 1748563200,
    "createdAt": 1748563200,
    "media": {
      "id": 1,
      "idMal": 1,
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "Sample description.",
      "season": "WINTER",
      "seasonYear": 1998,
      "seasonInt": 1,
      "episodes": 26,
      "duration": 24,
      "chapters": 0,
      "volumes": 0,
      "countryOfOrigin": "string",
      "isLicensed": false,
      "source": "ORIGINAL",
      "hashtag": "string",
      "updatedAt": 1748563200,
      "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/example.jpg",
      "genres": [
        "string"
      ],
      "synonyms": [
        "string"
      ],
      "averageScore": 87,
      "meanScore": 87,
      "popularity": 87,
      "isLocked": false,
      "trending": 100,
      "favourites": 87,
      "tags": [
        {}
      ],
      "isFavourite": false,
      "isFavouriteBlocked": false,
      "isAdult": false,
      "externalLinks": [
        {}
      ],
      "streamingEpisodes": [
        {}
      ],
      "rankings": [
        {}
      ],
      "siteUrl": "https://anilist.co/anime/1",
      "autoCreateForumThread": false,
      "isRecommendationBlocked": false,
      "isReviewBlocked": false,
      "modNotes": "string"
    },
    "user": {
      "id": 1,
      "name": "Sample Name",
      "about": "string",
      "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/example.jpg",
      "isFollowing": false,
      "isFollower": false,
      "isBlocked": false,
      "bans": {},
      "unreadNotificationCount": 1,
      "siteUrl": "https://anilist.co/anime/1",
      "donatorTier": 1,
      "donatorBadge": "string",
      "moderatorRoles": [
        "ADMIN"
      ],
      "createdAt": 1748563200,
      "updatedAt": 1748563200,
      "moderatorStatus": "string",
      "previousNames": [
        {}
      ]
    }
  },
  "reviews": {},
  "recommendations": {},
  "stats": {},
  "siteUrl": "https://anilist.co/anime/1",
  "autoCreateForumThread": false,
  "isRecommendationBlocked": false,
  "isReviewBlocked": false,
  "modNotes": "string"
}
