=== api-evangelist/anilist/json-schema/anilist-medialistcollection-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/anilist/refs/heads/main/json-schema/anilist-medialistcollection-schema.json",
  "title": "MediaListCollection",
  "description": "List of anime or manga",
  "type": "object",
  "properties": {
    "lists": {
      "type": "array",
      "items": {
        "$ref": "./anilist-medialistgroup-schema.json"
      },
      "description": "Grouped media list entries"
    },
    "user": {
      "$ref": "./anilist-user-schema.json",
      "description": "The owner of the list"
    },
    "hasNextChunk": {
      "type": "boolean",
      "description": "If there is another chunk"
    },
    "statusLists": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "$ref": "./anilist-medialist-schema.json"
        }
      },
      "description": "A map of media list entry arrays grouped by status",
      "deprecated": true
    },
    "customLists": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "$ref": "./anilist-medialist-schema.json"
        }
      },
      "description": "A map of media list entry arrays grouped by custom lists",
      "deprecated": true
    }
  }
}

=== api-evangelist/anilist/examples/anilist-medialistcollection-example.json
{
  "lists": [
    {}
  ],
  "user": {
    "id": 1,
    "name": "Sample Name",
    "about": "string",
    "avatar": {
      "large": "string",
      "medium": "string"
    },
    "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/example.jpg",
    "isFollowing": false,
    "isFollower": false,
    "isBlocked": false,
    "bans": {},
    "options": {
      "titleLanguage": "ROMAJI",
      "displayAdultContent": false,
      "airingNotifications": false,
      "profileColor": "#3DB4F2",
      "notificationOptions": [
        {}
      ],
      "timezone": "string",
      "activityMergeTime": 1748563200,
      "staffNameLanguage": "ROMAJI_WESTERN",
      "restrictMessagesToFollowing": false,
      "disabledListActivity": [
        {}
      ]
    },
    "mediaListOptions": {},
    "favourites": {},
    "statistics": {},
    "unreadNotificationCount": 1,
    "siteUrl": "https://anilist.co/anime/1",
    "donatorTier": 1,
    "donatorBadge": "string",
    "moderatorRoles": [
      "ADMIN"
    ],
    "createdAt": 1748563200,
    "updatedAt": 1748563200,
    "stats": {},
    "moderatorStatus": "string",
    "previousNames": [
      {}
    ]
  },
  "hasNextChunk": false,
  "statusLists": [
    [
      {}
    ]
  ],
  "customLists": [
    [
      {}
    ]
  ]
}
