=== api-evangelist/anilist/json-schema/anilist-airingschedule-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/anilist/refs/heads/main/json-schema/anilist-airingschedule-schema.json",
  "title": "AiringSchedule",
  "description": "Media Airing Schedule. NOTE: We only aim to guarantee that FUTURE airing data is present and accurate.",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "description": "The id of the airing schedule item"
    },
    "airingAt": {
      "type": "integer",
      "description": "The time the episode airs at"
    },
    "timeUntilAiring": {
      "type": "integer",
      "description": "Seconds until episode starts airing"
    },
    "episode": {
      "type": "integer",
      "description": "The airing episode number"
    },
    "mediaId": {
      "type": "integer",
      "description": "The associate media id of the airing episode"
    },
    "media": {
      "$ref": "./anilist-media-schema.json",
      "description": "The associate media of the airing episode"
    }
  },
  "required": [
    "id",
    "airingAt",
    "timeUntilAiring",
    "episode",
    "mediaId"
  ]
}

=== api-evangelist/anilist/examples/anilist-airingschedule-example.json
{
  "id": 1,
  "airingAt": 1748563200,
  "timeUntilAiring": 1748563200,
  "episode": 26,
  "mediaId": 1,
  "media": {
    "id": 1,
    "idMal": 1,
    "title": {
      "romaji": "Cowboy Bebop",
      "english": "Cowboy Bebop",
      "native": "カウボーイビバップ",
      "userPreferred": "string"
    },
    "type": "ANIME",
    "format": "TV",
    "status": "FINISHED",
    "description": "Sample description.",
    "startDate": {
      "year": 1998,
      "month": 4,
      "day": 3
    },
    "endDate": {
      "year": 1998,
      "month": 4,
      "day": 3
    },
    "season": "WINTER",
    "seasonYear": 1998,
    "seasonInt": 1,
    "episodes": 26,
    "duration": 24,
    "chapters": 0,
    "volumes": 0,
    "countryOfOrigin": "string",
    "isLicensed": false,
    "source": "ORIGINAL",
    "hashtag": "string",
    "trailer": {},
    "updatedAt": 1748563200,
    "coverImage": {
      "extraLarge": "string",
      "large": "string",
      "medium": "string",
      "color": "#3DB4F2"
    },
    "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/example.jpg",
    "genres": [
      "string"
    ],
    "synonyms": [
      "string"
    ],
    "averageScore": 87,
    "meanScore": 87,
    "popularity": 87,
    "isLocked": false,
    "trending": 100,
    "favourites": 87,
    "tags": [
      {}
    ],
    "relations": {},
    "characters": {},
    "staff": {},
    "studios": {},
    "isFavourite": false,
    "isFavouriteBlocked": false,
    "isAdult": false,
    "nextAiringEpisode": {
      "id": 1,
      "airingAt": 1748563200,
      "timeUntilAiring": 1748563200,
      "episode": 26,
      "mediaId": 1
    },
    "airingSchedule": {},
    "trends": {},
    "externalLinks": [
      {}
    ],
    "streamingEpisodes": [
      {}
    ],
    "rankings": [
      {}
    ],
    "mediaListEntry": {
      "id": 1,
      "userId": 1,
      "mediaId": 1,
      "status": "CURRENT",
      "score": 9.0,
      "progress": 1,
      "progressVolumes": 0,
      "repeat": 1748563200,
      "priority": 1,
      "private": false,
      "notes": "string",
      "hiddenFromStatusLists": false,
      "customLists": {},
      "advancedScores": {},
      "updatedAt": 1748563200,
      "createdAt": 1748563200
    },
    "reviews": {},
    "recommendations": {},
    "stats": {},
    "siteUrl": "https://anilist.co/anime/1",
    "autoCreateForumThread": false,
    "isRecommendationBlocked": false,
    "isReviewBlocked": false,
    "modNotes": "string"
  }
}
