=== api-evangelist/anilist/json-schema/anilist-character-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/anilist/refs/heads/main/json-schema/anilist-character-schema.json",
  "title": "Character",
  "description": "A character that features in an anime or manga",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "description": "The id of the character"
    },
    "name": {
      "$ref": "./anilist-charactername-schema.json",
      "description": "The names of the character"
    },
    "image": {
      "$ref": "./anilist-characterimage-schema.json",
      "description": "Character images"
    },
    "description": {
      "type": "string",
      "description": "A general description of the character"
    },
    "gender": {
      "type": "string",
      "description": "The character's gender. Usually Male, Female, or Non-binary but can be any string."
    },
    "dateOfBirth": {
      "$ref": "./anilist-fuzzydate-schema.json",
      "description": "The character's birth date"
    },
    "age": {
      "type": "string",
      "description": "The character's age. Note this is a string, not an int, it may contain further text and additional ages."
    },
    "bloodType": {
      "type": "string",
      "description": "The characters blood type"
    },
    "isFavourite": {
      "type": "boolean",
      "description": "If the character is marked as favourite by the currently authenticated user"
    },
    "isFavouriteBlocked": {
      "type": "boolean",
      "description": "If the character is blocked from being added to favourites"
    },
    "siteUrl": {
      "type": "string",
      "description": "The url for the character page on the AniList website"
    },
    "media": {
      "$ref": "./anilist-mediaconnection-schema.json",
      "description": "Media that includes the character"
    },
    "updatedAt": {
      "type": "integer",
      "deprecated": true
    },
    "favourites": {
      "type": "integer",
      "description": "The amount of user's who have favourited the character"
    },
    "modNotes": {
      "type": "string",
      "description": "Notes for site moderators"
    }
  },
  "required": [
    "id",
    "isFavourite",
    "isFavouriteBlocked"
  ]
}

=== api-evangelist/anilist/examples/anilist-character-example.json
{
  "id": 1,
  "name": {
    "first": "string",
    "middle": "string",
    "last": "string",
    "full": "string",
    "native": "カウボーイビバップ",
    "alternative": [
      "カウボーイビバップ"
    ],
    "alternativeSpoiler": [
      "カウボーイビバップ"
    ],
    "userPreferred": "string"
  },
  "image": {
    "large": "string",
    "medium": "string"
  },
  "description": "Sample description.",
  "gender": "string",
  "dateOfBirth": {
    "year": 1998,
    "month": 4,
    "day": 3
  },
  "age": "string",
  "bloodType": "string",
  "isFavourite": false,
  "isFavouriteBlocked": false,
  "siteUrl": "https://anilist.co/anime/1",
  "media": {},
  "updatedAt": 1748563200,
  "favourites": 87,
  "modNotes": "string"
}
