=== api-evangelist/anilist/json-schema/anilist-threadcomment-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/anilist/refs/heads/main/json-schema/anilist-threadcomment-schema.json",
  "title": "ThreadComment",
  "description": "Forum Thread Comment",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "description": "The id of the comment"
    },
    "userId": {
      "type": "integer",
      "description": "The user id of the comment's owner"
    },
    "threadId": {
      "type": "integer",
      "description": "The id of thread the comment belongs to"
    },
    "comment": {
      "type": "string",
      "description": "The text content of the comment (Markdown)"
    },
    "likeCount": {
      "type": "integer",
      "description": "The amount of likes the comment has"
    },
    "isLiked": {
      "type": "boolean",
      "description": "If the currently authenticated user liked the comment"
    },
    "siteUrl": {
      "type": "string",
      "description": "The url for the comment page on the AniList website"
    },
    "createdAt": {
      "type": "integer",
      "description": "The time of the comments creation"
    },
    "updatedAt": {
      "type": "integer",
      "description": "The time of the comments last update"
    },
    "thread": {
      "$ref": "./anilist-thread-schema.json",
      "description": "The thread the comment belongs to"
    },
    "user": {
      "$ref": "./anilist-user-schema.json",
      "description": "The user who created the comment"
    },
    "likes": {
      "type": "array",
      "items": {
        "$ref": "./anilist-user-schema.json"
      },
      "description": "The users who liked the comment"
    },
    "childComments": {
      "type": "object",
      "description": "The comment's child reply comments"
    },
    "isLocked": {
      "type": "boolean",
      "description": "If the comment tree is locked and may not receive replies or edits"
    }
  },
  "required": [
    "id",
    "likeCount",
    "createdAt",
    "updatedAt"
  ]
}

=== api-evangelist/anilist/examples/anilist-threadcomment-example.json
{
  "id": 1,
  "userId": 1,
  "threadId": 1,
  "comment": "string",
  "likeCount": 1,
  "isLiked": false,
  "siteUrl": "https://anilist.co/anime/1",
  "createdAt": 1748563200,
  "updatedAt": 1748563200,
  "thread": {
    "id": 1,
    "title": "Cowboy Bebop",
    "body": "string",
    "userId": 1,
    "replyUserId": 1,
    "replyCommentId": 1,
    "replyCount": 1,
    "viewCount": 1,
    "isLocked": false,
    "isSticky": false,
    "isSubscribed": false,
    "likeCount": 1,
    "isLiked": false,
    "repliedAt": 1748563200,
    "createdAt": 1748563200,
    "updatedAt": 1748563200,
    "user": {
      "id": 1,
      "name": "Sample Name",
      "about": "string",
      "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/example.jpg",
      "isFollowing": false,
      "isFollower": false,
      "isBlocked": false,
      "bans": {},
      "unreadNotificationCount": 1,
      "siteUrl": "https://anilist.co/anime/1",
      "donatorTier": 1,
      "donatorBadge": "string",
      "moderatorRoles": [
        "ADMIN"
      ],
      "createdAt": 1748563200,
      "updatedAt": 1748563200,
      "moderatorStatus": "string",
      "previousNames": [
        {}
      ]
    },
    "replyUser": {
      "id": 1,
      "name": "Sample Name",
      "about": "string",
      "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/example.jpg",
      "isFollowing": false,
      "isFollower": false,
      "isBlocked": false,
      "bans": {},
      "unreadNotificationCount": 1,
      "siteUrl": "https://anilist.co/anime/1",
      "donatorTier": 1,
      "donatorBadge": "string",
      "moderatorRoles": [
        "ADMIN"
      ],
      "createdAt": 1748563200,
      "updatedAt": 1748563200,
      "moderatorStatus": "string",
      "previousNames": [
        {}
      ]
    },
    "likes": [
      {}
    ],
    "siteUrl": "https://anilist.co/anime/1",
    "categories": [
      {}
    ],
    "mediaCategories": [
      {}
    ]
  },
  "user": {
    "id": 1,
    "name": "Sample Name",
    "about": "string",
    "avatar": {
      "large": "string",
      "medium": "string"
    },
    "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/example.jpg",
    "isFollowing": false,
    "isFollower": false,
    "isBlocked": false,
    "bans": {},
    "options": {
      "titleLanguage": "ROMAJI",
      "displayAdultContent": false,
      "airingNotifications": false,
      "profileColor": "#3DB4F2",
      "notificationOptions": [
        {}
      ],
      "timezone": "string",
      "activityMergeTime": 1748563200,
      "staffNameLanguage": "ROMAJI_WESTERN",
      "restrictMessagesToFollowing": false,
      "disabledListActivity": [
        {}
      ]
    },
    "mediaListOptions": {},
    "favourites": {},
    "statistics": {},
    "unreadNotificationCount": 1,
    "siteUrl": "https://anilist.co/anime/1",
    "donatorTier": 1,
    "donatorBadge": "string",
    "moderatorRoles": [
      "ADMIN"
    ],
    "createdAt": 1748563200,
    "updatedAt": 1748563200,
    "stats": {},
    "moderatorStatus": "string",
    "previousNames": [
      {}
    ]
  },
  "likes": [
    {
      "id": 1,
      "name": "Sample Name",
      "about": "string",
      "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/example.jpg",
      "isFollowing": false,
      "isFollower": false,
      "isBlocked": false,
      "bans": {},
      "unreadNotificationCount": 1,
      "siteUrl": "https://anilist.co/anime/1",
      "donatorTier": 1,
      "donatorBadge": "string",
      "moderatorRoles": [
        "ADMIN"
      ],
      "createdAt": 1748563200,
      "updatedAt": 1748563200,
      "moderatorStatus": "string",
      "previousNames": [
        {}
      ]
    }
  ],
  "childComments": {},
  "isLocked": false
}
